services:
  db:
    image: postgres:15
    container_name: testbotshop_db
    environment:
      POSTGRES_DB: testbotshop_db
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - testbotshop_network

volumes:
  postgres_data:

networks:
  testbotshop_network:
    driver: bridge
